grails-app/domain/org/grails/plugin/License.groovy
package org.grails.plugin

/**
 * Stores details of software licenses.
 */
class License {
    String name
    String url

    static constraints = {
        name blank: false
        url url: true
    }
}

grails-app/domain/org/grails/plugin/PluginPendingApproval.groovy
package org.grails.plugin

import org.grails.auth.User
import org.grails.common.ApprovalStatus
import org.grails.content.GenericApprovalResponse
import org.joda.time.DateTime
import org.joda.time.Days

class PluginPendingApproval {

    String name
    String versionNumber
    String scmUrl
    ApprovalStatus status = ApprovalStatus.PENDING
    User submittedBy
    String notes
    DateTime dateCreated

    static constraints = {
        name blank: false, unique: 'versionNumber', matches:/\S+/
        versionNumber blank: false
        scmUrl blank: false
        status blank: false
        notes nullable: true, blank: true
        submittedBy nullable: false
    }

    static mapping = {
        notes type: 'text'
    }

    static namedQueries = {
        pending {
            eq('status', ApprovalStatus.PENDING)
        }
    }

    def setDisposition(GenericApprovalResponse genericApprovalResponse) {
        this.status = genericApprovalResponse.status
        this.save(flush: true)
    }

    List<GenericApprovalResponse> getGenericApprovalResponses() {
        def query = GenericApprovalResponse.where {
            whatType == this.class.name && whatId == this.id
        }
        return query.list(sort: 'id', order: 'asc')
    }

    def getIsNew() {
        (dateCreated > (new DateTime() - Days.days(14)))
    }
}

grails-app/controllers/org/grails/ErrorController.groovy
package org.grails

class ErrorController {
    def serverError() {}
    def devError() {}
    def notFound() {}
}

grails-app/controllers/org/grails/plugin/PendingReleaseController.groovy
package org.grails.plugin

import grails.converters.*

class PendingReleaseController {

    static scaffold = PendingRelease

    def pluginDeployService

    def deploy(Long id) {
        def pr = PendingRelease.get(id)

        if(pr) {
            pluginDeployService.deployRelease(pr)
            flash.message = "Release deployed"
            redirect action:"list"
        }
        else {
            flash.message = "Release not found"
            redirect action:"list"
        }
    }

    /**
     * Returns the status of the given pending release, or a 404 if it doesn't
     * exist.
     */
    def status(String name, String version) {
        def pr = PendingRelease.findByPluginNameAndPluginVersion(name, version)
        if (!pr) {
            def pluginRelease = PluginRelease.where {
                plugin.name == name && releaseVersion == version
            }.get()
            if (pluginRelease) pr = [status: ReleaseStatus.COMPLETED]
        }

        if (pr) {
            withFormat {
                text {
                    render text: pr.status.toString()
                }
                json {
                    render([status: pr.status.toString()] as JSON)
                }
                xml {
                    render contentType: "application/xml", {
                        status pr.status.toString()
                    }
                }
            }
        }
        else {
            response.sendError 404
        }
    }
}

grails-app/controllers/org/grails/plugin/PluginAdminController.groovy
package org.grails.plugin

class PluginAdminController {

	def scaffold = Plugin

    def list() {
        params.max = Math.min(params.max ? params.int('max') : 10, 100)
        [pluginList: Plugin.list(params), pluginTotal: Plugin.count()]
    }

    def search(String q) {
      def max = Math.min(params.max ? params.int('max') : 10, 100)
      def searchResults = Plugin.search(q, [max: max, offset: params.int('offset', 0)])
      render view:"list", model:[pluginList: searchResults.results, pluginTotal:searchResults.total]        
    }

    def show() {
        def plugin = Plugin.get(params.id)
        if (!plugin) {
            flash.message = "Plugin not found"
            redirect(action: "list")
        }
        else {
            [plugin: plugin]
        }
    }

    // One time use data migration action
    def dataSource
    def fixTabs() {
        def sql = new groovy.sql.Sql(dataSource)

        sql.withTransaction {
            sql.eachRow("select * from plugin") { row ->

                def descId = row.description_id
                def installId = row.installation_id
                def faqId = row.faq_id
                def screenshotsId = row.screenshots_id

                def currentId = descId
                def name = row.name

                updateTab(sql, descId, "description", name, row.id )
                updateTab(sql, installId, "installation", name, row.id )
                updateTab(sql, faqId, "faq", name, row.id )
                updateTab(sql, screenshotsId, "screenshots", name, row.id )
            }


        }
        render "Done."
    }

    private updateTab(sql, id, type, pluginName, pluginId) {
        def key = "plugin-$pluginName-$type".toString()
        def current = sql.firstRow("select * from content where class = ? and id = ?", ["org.grails.plugin.PluginTab", id])
        def existing = sql.firstRow("select * from content where class = ? and title = ?", ["org.grails.plugin.PluginTab", key])

        
        if(current.title != key) {
            if(existing) {
                sql.executeUpdate "update plugin set "+type+"_id = ? where id = ?", [existing.id, pluginId]
                sql.executeUpdate "update content set body = ? where id = ?", [current.body, existing.id]
            }
            else {
                sql.executeUpdate "update content set title = ? where class = ? and id = ?", [key, "org.grails.plugin.PluginTab", id]    
            }                    
        }        
    }


    def searchableService
    def update(Long id, Long version) {

        def p = Plugin.get(id)
        println "updating plugin $p"
        if (!p) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: '${domainClass.propertyName}.label', default: 'Plugin'), id])
            redirect(action: "list")
            return
        }

        if (version != null) {
            if (p.version > version) {
                println "VERSION MISMATCH"
                p.errors.rejectValue("version", "default.optimistic.locking.failure",
                          [message(code: '${domainClass.propertyName}.label', default: 'Plugin')] as Object[],
                          "Another user has updated this Plugin while you were editing")
                render(view: "edit", model: [pluginInstance: p])
                return
            }
        }

        p.properties = params

        try {
            searchableService.stopMirroring()
            if (!p.save(flush: true)) {
                println "VALIDATION ERRORS ${p.errors}"
                render(view: "edit", model: [pluginInstance: p])
                return
            }
            println "SAVED!"
        }
        finally {
             searchableService.startMirroring()

        }
            flash.message = message(code: 'default.updated.message', args: [message(code: '${domainClass.propertyName}.label', default: 'Plugin'), p.id])
        redirect(action: "show", id: p.id)
    }
}

grails-app/controllers/org/grails/plugin/PluginController.groovy
package org.grails.plugin

import grails.converters.*
import grails.gorm.*
import org.grails.taggable.*
import org.apache.commons.codec.digest.DigestUtils
import org.grails.tags.TagNotFoundException
import org.grails.common.ApprovalStatus
import org.compass.core.engine.SearchEngineQueryParseException

class PluginController {

    def dateService
    def pluginService
    def tagService
    def wikiPageService
    def cacheService

    def legacyHome() {
        redirect action: "list", permanent: true
    }

    def addTag(String id, String tag) {
        def p = Plugin.findByName(id)
        if(p) {
            if(request.method == "POST") {
                p.addTag(tag)
            }
            def tags = p.tags.collect {
                [  name: it]
            }
            def data = [ tagResults: tags ]
            render data as JSON            
        }
        else {
            render status: 404
        }

    }
    def removeTag(String id, String tag) {
        def p = Plugin.findByName(id)
        if(p) {
            if(request.method == "POST") {
                p.removeTag(tag)
            }
            def tags = p.tags.collect {
                [  name: it]
            }
            def data = [ tagResults: tags ]
            render data as JSON            
        }
        else {
            render status: 404
        }

    }    
    def list() {
        try {
            def maxResults = params.int("max",10)
            def offset = params.int("offset", 0)

            def plugins
            def pluginCount
            def filter = params.filter?.toString() ?: "featured"
            if (params.tag) {
                filter = "all"
                (plugins, pluginCount) = pluginService.listPluginsByTagWithTotal(params.tag, max: maxResults, offset: offset)
            }
            else {
                (plugins, pluginCount) = pluginService."list${filter.capitalize()}PluginsWithTotal"(max: maxResults, offset: offset)
            }

            def allTags = new DetachedCriteria(org.grails.taggable.Tag).property("name").list()
            def tags = tagService.getPluginTagArray()
            def model = [ allTags:allTags, tags: tags, plugins: plugins, pluginCount: pluginCount ]
            if (filter) model["activeFilter"] = filter
            if (params.tag) model["activeTag"] = params.tag

            model["home"] = (filter == "featured" && !model["activeTag"])
            return model
        }
        catch (TagNotFoundException ex) {
            flash.message = "Tag not found"
            redirect action: "list"
        }
    }

    def show(String id) {
        def plugin = Plugin.findByName(id)

        // Redirect to the list page if the plugin doesn't exist
        if (!plugin) {
            flash.message = "Plugin not found"
            redirect action: 'list'
            return
        }

        def tags = tagService.getPluginTagArray()
        def allTags = new DetachedCriteria(org.grails.taggable.Tag).property("name").list()
        [ plugin: plugin, tags: tags, allTags: allTags ]
    }

    def editPlugin(String id) {
        show(id)
    }

    def updatePlugin(String id) {
        def plugin = Plugin.findByName(id)
        if(plugin && params['plugin']) {
            plugin.properties['summary'] = params['plugin']
            if(plugin.save()) {
                def installation = params['plugin']['installation'] 
                def description= params['plugin']['description'] 

                try {
                  def pluginTabInstallation = wikiPageService.createOrUpdatePluginTab(
                    "plugin-${id}-installation",
                    installation.body,
                    request.user,
                    params.long('plugin.installation.version'))

                  def pluginTabDescription = wikiPageService.createOrUpdatePluginTab(
                    "plugin-${id}-description",
                    description.body,
                    request.user,
                    params.long('plugin.description.version'))              
                    if(pluginTabInstallation.hasErrors() || pluginTabDescription.hasErrors()) {
                        render view:"editPlugin", model:show(id)
                    }
                    else {
                        redirect uri:"/plugin/$id" 
                    }                  

                    cacheService?.removeWikiText('pluginInfo_summary_' + plugin?.name)
                }
                catch( javax.persistence.OptimisticLockException e) {
                    flash.message = e.message
                    render view:"editPlugin", model:show(id)
                    return
                }
     
            } 
            else {
                render view:"editPlugin", model:show(id)
            }

        }
        else {
            render status:404
        }
    }


    def submitPlugin() {
        def pluginPendingApproval = new PluginPendingApproval(
            submittedBy: request.user,
            status: ApprovalStatus.PENDING
        )
        if (request.method == "POST") {
            pluginPendingApproval.name = params.name
            pluginPendingApproval.scmUrl = params.scmUrl
            pluginPendingApproval.versionNumber = params.versionNumber
            pluginPendingApproval.notes = params.notes

            pluginPendingApproval.validate()

            if (!pluginPendingApproval.hasErrors() && pluginPendingApproval.save(flush:true)) {
                flash.message = "Your plugin has been submitted for approval"
                redirect url: "/plugins/pending/${pluginPendingApproval?.id}"
            } else {
                flash.message = "Please correct the fields below"
                flash.next()
            }
        }
        [pluginPendingApproval: pluginPendingApproval]
    }

    def submissionReceived() {
    }

    def pendingPlugins() {
        params.max = Math.min(params.max ? params.int('max') : 10, 100)
        def tags = tagService.getPluginTagArray()
        [
                tags: tags,
                pluginPendingApprovalList: PluginPendingApproval.pending.list(params),
                pluginPendingApprovalTotal: PluginPendingApproval.pending.count()
        ]
    }

    def showPendingPlugin() {
        def pluginPendingApprovalInstance = PluginPendingApproval.get(params.id)
        if (!pluginPendingApprovalInstance) {
            redirect action: 'pendingPlugins'
        }

        [pluginPendingApprovalInstance: pluginPendingApprovalInstance]
    }

    def search() {
        if (params.q) {
            def tags = tagService.getPluginTagArray()
            try {
                def searchResult = Plugin.search(params.q, offset: params.offset)
                searchResult.results = searchResult.results.findAll{it}.unique { it.title }

                flash.message = "Found $searchResult.total results!"
                flash.next()
                render view: "list", model: [
                        query: params.q,
                        tags: tags,
                        searchResult: searchResult, 
                        plugins: searchResult.results, 
                        pluginCount: searchResult.total,
                        otherParams: [q: params.q] ]
            }
            catch (SearchEngineQueryParseException ex) {
                render view: "list", model: [tags: tags, parseException: true]
            }
            catch (org.apache.lucene.search.BooleanQuery.TooManyClauses ex) {
                render view: "list", model: [tags: tags, clauseException: true]
            }
        }
        else {
            redirect action: "list"
        }
    }

    //---- REST API --------------------------------------

    /**
     * Display all plugins or subset of using preferred content type. Only
     * JSON or XML supported at this point.
     */
    def apiList() {
        def pluginData = listPlugins(0, 'all')
        def pluginList = transformPlugins(pluginData.currentPlugins, pluginData.category)

        withFormat {
            json {
                render pluginList as JSON
            }
            xml {
                renderMapAsXml pluginList, "plugins"
            }
        }
    }

    /**
     * Display the details of one plugin in either JSON or XML form.
     */
    def apiShow() {
        if(params.name && params.version) {
            def p = params.name
            def v = params.version
            def release = PluginRelease.where {
                plugin.name == p && releaseVersion == v 
            }.get()

            if (release) {
                def plugin = transformPluginRelease(release)
                withFormat {
                    json {
                        render plugin as JSON        
                    }
                    xml {
                        renderMapAsXml plugin, "plugin"
                    }
                }
            }
            else {
                response.sendError 404
            }
        }
        else {
            def plugin = byName(params)
            if (!plugin) {
                response.sendError 404
                return
            }

            plugin = transformPlugin(plugin)
            withFormat {
                json {
                    render plugin as JSON
                }
                xml {
                    renderMapAsXml plugin, "plugin"
                }
            }
        }
    }

    /**
     * Plugin 'ping'. Should only be accessible from a PUT. It extracts
     * the location of the plugin's deployment repository from the request
     * and queues up a job to update the plugin's details in the database
     * from the POM and plugin descriptor stored in the repository.
     */
    def apiUpdate() {
        // Start by getting the named plugin if it exists.
        def plugin = Plugin.findByName(params.id)
        log.debug "Updating plugin [$plugin] via API"

grails-app/controllers/org/grails/plugin/PluginReleaseController.groovy
package org.grails.plugin

class PluginReleaseController {
    static scaffold = true
}

grails-app/controllers/org/grails/plugin/PluginTabController.groovy
package org.grails.plugin


class PluginTabController {
    static scaffold = PluginTab
}

grails-app/views/plugin/_pendingPlugin.gsp
<article class="item">
    <header>
        <h3>
            <a href="/plugins/pending/${pluginPendingApprovalInstance?.id}">
                ${pluginPendingApprovalInstance?.name}
                <g:if test="${pluginPendingApprovalInstance?.isNew}">
                    <g:img dir="img/page" file="new.png" />
                </g:if>
            </a>
        </h3>

        <p class="meta">
            version <strong>${pluginPendingApprovalInstance?.versionNumber}</strong>,
            approval status: <strong><common:approvalStatus status="${pluginPendingApprovalInstance?.status}" /></strong>,
            submitted by <a href="#">${pluginPendingApprovalInstance?.submittedBy?.login}</a>
            <prettytime:display date="${pluginPendingApprovalInstance?.dateCreated}"/>
        </p>
    </header>

    <div class="desc">
        <p>${pluginPendingApprovalInstance?.notes}</p>
    </div>
</article>

grails-app/views/plugin/_pluginRating.gsp
<div id="ratingCount${plugin.id}" class="ratingCount">${plugin.ratingCount} vote${plugin.ratingCount > 1 ? 's':''}</div>
<div id="pluginRating${plugin.id}" class="rating"></div>

<r:script>

    $('#pluginRating${plugin.id}').raty({path:'/img', readOnly:${plugin.userRating(request.user) ? true : false}, score:${plugin.avgRating ?: 0}, half:true, halfShow:true, click: function(score, evt) {

        <g:if test="${request.user}">
           $.ajax( { url:"${createLink(controller:"rateable", action:'rate', id:plugin.id)}", type:"POST", 
                     data: {rating: score, type:"plugin"}
            }) 

            var count = $('#ratingCount${plugin.id}').text()
            $('#ratingCount${plugin.id}').text(parseInt(count)+1)
            $('#pluginRating${plugin.id}').raty('readOnly', true)
        </g:if>
        <g:else>
            window.location = "${createLink(controller:"user", action:"login", params:[targetUri:request.forwardURI])}";
        </g:else>
    }})
</r:script>

grails-app/views/plugin/_pluginTags.gsp
<span>Tags :</span>
<span id="plugin-tags-${plugin.id}">
    <g:if test="${plugin.tags.size() > 0}">
        <g:each in="${plugin.tags}" var="tag" status="i"><g:if test="${i > 0}">, </g:if><a href="/plugins/tag/${tag}">${tag}</a></g:each>
    </g:if>
    <g:else>
        /
    </g:else>
</span>

<g:if test="${request.user != null}">
    <a href="#" id="plugin-tag-edit${plugin.id}"><img src="/img/icons/edit-tag.png"  /></a>
</g:if>
<g:else>
    <g:link controller="user" action="login" params="[targetUri:request.forwardURI]"><img src="/img/icons/edit-tag.png"  /></g:link>
</g:else>
<ul id="pluginTags${plugin.id}" data-plugin="${plugin.name}" style="display:none;">
    <g:each in="${plugin.tags}" var="tag"><li data-plugin="${plugin.name}">${tag}</li></g:each>    
</ul>
<r:script>
    var pluginTags = $('#pluginTags${plugin.id}')
    pluginTags.tagit({
        onTagAdded: onTagAddedFunction,
        onTagRemoved: onTagRemovedFunction,
        onTagClicked:onTagClickFunction,
        availableTags: tags
        
    });

    <g:if test="${request.user != null}">
        $('#plugin-tag-edit${plugin.id}').click(function() {
            $('#pluginTags${plugin.id} input').focus();
            $('#plugin-tags-${plugin.id}').hide();
            $('#pluginTags${plugin.id}').show();
            return false;
        });
        var timer;
        $('#pluginTags${plugin.id} input').blur(function(){
            $('#pluginTags${plugin.id} input').data("focus", "false");
            if (timer)
                clearTimeout(timer);
            timer = setInterval(function(){
                if ($('#pluginTags${plugin.id} input').data("focus") == "false") {
                    $('#plugin-tag-edit${plugin.id}').show();
                    $('#plugin-tags-${plugin.id}').show();
                    $('#pluginTags${plugin.id}').hide();
                    if ($("#pluginTags${plugin.id} li").length == 0) {
                        $('#plugin-tags-${plugin.id}').text("/");
                    } else {
                        var str = $("#pluginTags${plugin.id} li .tagit-label").map(function() {
                            return "<a href='/plugins/tag/" + $(this).text() + "'>" + $(this).text() + "</a>";
                        }).get().join(', ');
                        $('#plugin-tags-${plugin.id}').html(str);
                    }
                }
                clearTimeout(timer);
            },400);
        }).focus(function() {
            $('#pluginTags${plugin.id} input').data("focus", "true");
            $('#plugin-tag-edit${plugin.id}').hide();
            $('#plugin-tags-${plugin.id}').hide();
            $('#pluginTags${plugin.id}').show();
        });

    </g:if>
</r:script>

grails-app/views/plugin/_searchBar.gsp
<form class="search" action="/plugins/search" name="plugin-search" method="GET">
    <input type="text" id="q" name="q" value="${params.q?.encodeAsHTML()}" placeholder="Search for a plugin"/>
    <a href="#" id="search-button" class="btn btn-search">
        <i class="icon-search icon-white"></i>
    </a>
</form>

grails-app/views/plugin/_sideNav.gsp
<div class="aside">
    <g:if test="${!(actionName == "list")}">
        <aside class="search">
            <g:render template="searchBar" />
        </aside>
    </g:if>
    <aside class="filters">
        <h3>Filters<g:if test="${activeFilter != 'all'}">&nbsp;&nbsp;&nbsp;<a style="font-size: smaller;" href="/plugins?filter=all">clear filter</a></g:if></h3>
        <ul>
            <li <g:if test="${activeFilter == 'all'}">class="active"</g:if>>
                <a href="/plugins?filter=all">
                    <g:img dir="img/icons" file="plugin.png" />
                    All Plugins
                </a>
            </li>            
            <li <g:if test="${activeFilter == 'featured'}">class="active"</g:if>><a href="/plugins?filter=featured"><g:img dir="img/plugin" file="featured.png" /> Featured</a></li>
            <li <g:if test="${activeFilter == 'installed'}">class="active"</g:if>><a href="/plugins?filter=installed"><g:img dir="img/plugin" file="topInstalled.png" /> Top Installed</a></li>
            <li <g:if test="${activeFilter == 'popular'}">class="active"</g:if>><a href="/plugins?filter=popular"><g:img dir="img" file="star-on.png" /> Popular</a></li>
            <li <g:if test="${activeFilter == 'recentlyUpdated'}">class="active"</g:if>><a href="/plugins?filter=recentlyUpdated"><g:img dir="img/plugin" file="recentlyUpdated.png" /> Recently Updated</a></li>
            <li <g:if test="${activeFilter == 'newest'}">class="active"</g:if>><a href="/plugins?filter=newest"><g:img dir="img/plugin" file="newest.png" /> Newest</a></li>
            <li class="last<g:if test="${activeFilter == 'supported'}"> active</g:if>"><a href="/plugins?filter=supported"><g:img dir="img/plugin" file="supported.png" /> Supported by SpringSource</a></li>
            <li>
                <a href="/plugins/pending">
                    <g:img dir="img/icons" file="pending.png"/>
                    Pending Plugins
                </a>
            </li>                
        </ul>
    </aside>

    <aside class="tags">
        <h3>Popular tags<g:if test="${activeTag}">&nbsp;&nbsp;&nbsp;<a style="font-size: smaller;" href="/plugins?filter=all">clear tag</a></g:if></h3>
        <ul>
            <g:each in="${tags[0]}" var="tag" status="i">
                <li class="
                    <g:if test="${activeTag == tag}"> active</g:if>
                    <g:if test="${i == tags.size() - 1}"> last</g:if>
                "><a href="/plugins/tag/${tag}">${tag.capitalize()}</a></li>
            </g:each>
            <g:each in="${tags[1]}" var="tag" status="i">
                <li class="
                    <g:if test="${activeTag == tag}"> active</g:if>
                    <g:if test="${i == tags.size() - 1}"> last</g:if>
                "><a href="/plugins/tag/${tag}">${tag.capitalize()}</a></li>
            </g:each>
        </ul>
    </aside>

</div>

grails-app/views/plugin/_tagSetup.gsp
<r:script>
    var tagsInitialized = false;
    var tags = [
        ${allTags.collect { "\"$it\""}.join(',')}
    ]

    var onTagAddedFunction =  function(event, tag) {
        if(${request.user == null} && tagsInitialized) {
            window.location = "${createLink(controller:'user', action:'login')}";
        }
        else if(tagsInitialized){
            var link = "${createLink(action:"addTag")}";
            var label = pluginTags.tagit('tagLabel', tag)
            var plugin = $("#" + this.id).data("plugin")
            $.ajax({url:link, type:"POST",data: {tag: label, id: plugin}})
        }
    }
    var onTagRemovedFunction =  function(event, tag) {
        if(${request.user == null} && tagsInitialized) {
            window.location = "${createLink(controller:'user', action:'login')}";
        }
        else if(tagsInitialized){
            var link = "${createLink(action:"removeTag")}";
            var label = pluginTags.tagit('tagLabel', tag)
            var plugin = $("#" + this.id).data("plugin")
            $.ajax({url:link, type:"POST",data: {tag: label, id: plugin}})

        }
    }    
    var onTagClickFunction = function(event, tag) {
            var label = pluginTags.tagit('tagLabel', tag)
            var link = "/plugins/tag/" + label;

            window.location = link;
    }     
</r:script>

grails-app/views/plugin/submissionReceived.gsp
<head>
    <meta content="master" name="layout"/>
    <title>Grails Plugin Submitted for Approval</title>
    <r:require modules="plugin"/>
</head>

<body>

<div id="content" class="content-aside-2" role="main">

    <div class="aside">
        <g:render template="sideSubmission" />
    </div>

    <section id="main">

        <article>
            <h3>Submit Plugin for Approval</h3>

            <g:if test="${flash.message}">
                <div class="alert alert-info">${flash.message}</div>
            </g:if>

            <p>Thank you for submitting your plugin. We will get back to you within 24 hours with either an approval, or
            a rejection with an explanation.</p>

        </article>
    </section>

</div>

</body>

grails-app/views/plugin/submitPlugin.gsp
<head>
    <meta content="master" name="layout"/>
    <title>Submit a Grails Plugin for Approval</title>
    <r:require modules="plugin"/>
</head>

<body>

<div id="content" class="content-aside" role="main">

    <div class="aside">
        <g:render template="sideSubmission"/>
    </div>

    <section id="main" class="plugins">

        <article>
            <h2>Submit Plugin for Approval</h2>

            <g:if test="${flash.message}">
                <div class="alert alert-${pluginPendingApproval.errors.errorCount > 0 ? 'error' : 'info'}">${flash.message}</div>
            </g:if>

            <g:form action="submitPlugin" class="content-form padding-top">

                <g:hiddenField name="status" value="${pluginPendingApproval.status}"/>

                <div class="control-group ${hasErrors(bean: pluginPendingApproval, field: 'name', 'error')}">
                    <label for="name">Plugin Name <small>(whatever you passed to the create-plugin command)</small></label>

                    <div class="controls">
                        <g:textField name="name" value="${params.name}" required="required" class="input-fullsize"/>
                        <g:if test="${pluginPendingApproval.errors.getFieldErrorCount('name') > 0}">
                            <p class="error-block">${pluginPendingApproval.errors.getFieldError('name').defaultMessage}</p>
                        </g:if>
                    </div>
                </div>

                <div class="control-group ${hasErrors(bean: pluginPendingApproval, field: 'versionNumber', 'error')}">
                    <label for="versionNumber">Version Number <small>(example: 0.0.1)</small></label>
                    <div class="controls">
                        <g:textField name="versionNumber" value="${params.versionNumber}" required="required" class="input-fullsize"/>
                        <g:if test="${pluginPendingApproval.errors.getFieldErrorCount('versionNumber') > 0}">
                            <p class="help-block">${pluginPendingApproval.errors.getFieldError('versionNumber').defaultMessage}</p>
                        </g:if>
                        <p class="help-block">This is important indicating versions if you need to re-submit plugins</p>
                    </div>
                </div>

                <div class="control-group ${hasErrors(bean: pluginPendingApproval, field: 'scmUrl', 'error')}">
                    <label for="scmUrl">Repository URL <small>(for example, http://www.github.com/grails/grails-core)</small></label>
                    <div class="controls">
                        <g:textField name="scmUrl" value="${params.scmUrl}" required="required" class="input-fullsize"/>
                        <g:if test="${pluginPendingApproval.errors.getFieldErrorCount('scmUrl') > 0}">
                            <p class="error-block">${pluginPendingApproval.errors.getFieldError('scmUrl').defaultMessage}</p>
                        </g:if>
                    </div>
                </div>

                <div class="control-group">
                    <label for="notes">Plugin Description</label>

                    <div class="controls">
                        <g:textArea rows="8" cols="60" name="notes" value="${params.notes}" required="required" class="input-fullsize"></g:textArea>
                    </div>
                </div>

                <p>
                    <em>Please note that in order for a plugin to be approved, you must make sure that the plugin is well
                    documented, which includes a full description and usage.</em>
                </p>

                <div class="form-actions">
                    <g:submitButton name="submit" value="Submit for Approval" class="btn"/>
                </div>

            </g:form>
        </article>

    </section>

</div>

</body>