grails-app/controllers/org/grails/community/TestimonialAdminController.groovy
package org.grails.community

import org.grails.content.GenericApprovalResponse
import org.grails.common.ApprovalStatus

class TestimonialAdminController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def genericApprovalResponseService

    def index = {
        redirect(action: "list", params: params)
    }

    def list = {
        params.max = Math.min(params.max ? params.int('max') : 10, 100)
        [testimonialInstanceList: Testimonial.list(params), testimonialInstanceTotal: Testimonial.count()]
    }

    def create = {
        def testimonialInstance = new Testimonial()
        testimonialInstance.properties = params
        return [testimonialInstance: testimonialInstance]
    }

    def save = {
        def testimonialInstance = new Testimonial(params)
        if (testimonialInstance.save(flush: true)) {
            flash.message = "${message(code: 'default.created.message', args: [message(code: 'testimonial.label', default: 'Testimonial'), testimonialInstance.id])}"
            redirect(action: "show", id: testimonialInstance.id)
        }
        else {
            render(view: "create", model: [testimonialInstance: testimonialInstance])
        }
    }

    def show = {
        def testimonialInstance = Testimonial.get(params.id)
        if (!testimonialInstance) {
            flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'testimonial.label', default: 'Testimonial'), params.id])}"
            redirect(action: "list")
        }
        else {
            [testimonialInstance: testimonialInstance]
        }
    }

    def edit = {
        def testimonialInstance = Testimonial.get(params.id)
        if (!testimonialInstance) {
            flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'testimonial.label', default: 'Testimonial'), params.id])}"
            redirect(action: "list")
        }
        else {
            return [testimonialInstance: testimonialInstance]
        }
    }

    def disposition = {
        def testimonialInstance = Testimonial.get(params.id)
        if (params.featured) {
            testimonialInstance.featured = true
            testimonialInstance.save(flush: true)
        }

        def genericApprovalResponse = new GenericApprovalResponse(
                submittedBy: testimonialInstance.submittedBy,
                moderatedBy: request.user,
                whatType: testimonialInstance.class.name,
                whatId: testimonialInstance.id,
                responseText: params.responseText,
                status: ApprovalStatus.valueOf(params.status)
        )

        if (!genericApprovalResponse.hasErrors() && genericApprovalResponse.save(flush: true)) {
            if (genericApprovalResponseService.linkAndfirePendingApproval(genericApprovalResponse)) {
                flash.message = "Response was submitted to ${genericApprovalResponse.submittedBy?.login} (${genericApprovalResponse.submittedBy?.email})"
            }
            else {
                flash.message = "Unable to process the request including sending the email."
            }
        }
        else {
            println genericApprovalResponse.errors?.inspect()
            flash.message = "Unable to save response."
        }
        redirect action: 'show', id: testimonialInstance.id
    }

    def update = {
        def testimonialInstance = Testimonial.get(params.id)
        if (testimonialInstance) {
            if (params.version) {
                def version = params.version.toLong()
                if (testimonialInstance.version > version) {
                    
                    testimonialInstance.errors.rejectValue("version", "default.optimistic.locking.failure", [message(code: 'testimonial.label', default: 'Testimonial')] as Object[], "Another user has updated this Testimonial while you were editing")
                    render(view: "edit", model: [testimonialInstance: testimonialInstance])
                    return
                }
            }
            testimonialInstance.properties = params
            if (!testimonialInstance.hasErrors() && testimonialInstance.save(flush: true)) {
                flash.message = "${message(code: 'default.updated.message', args: [message(code: 'testimonial.label', default: 'Testimonial'), testimonialInstance.id])}"
                redirect(action: "show", id: testimonialInstance.id)
            }
            else {
                render(view: "edit", model: [testimonialInstance: testimonialInstance])
            }
        }
        else {
            flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'testimonial.label', default: 'Testimonial'), params.id])}"
            redirect(action: "list")
        }
    }

    def delete = {
        def testimonialInstance = Testimonial.get(params.id)
        if (testimonialInstance) {
            try {
                testimonialInstance.delete(flush: true)
                flash.message = "${message(code: 'default.deleted.message', args: [message(code: 'testimonial.label', default: 'Testimonial'), params.id])}"
                redirect(action: "list")
            }
            catch (org.springframework.dao.DataIntegrityViolationException e) {
                flash.message = "${message(code: 'default.not.deleted.message', args: [message(code: 'testimonial.label', default: 'Testimonial'), params.id])}"
                redirect(action: "show", id: params.id)
            }
        }
        else {
            flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'testimonial.label', default: 'Testimonial'), params.id])}"
            redirect(action: "list")
        }
    }
}

grails-app/views/testimonialAdmin/_form.gsp
<%@ page import="org.grails.community.Testimonial" %>

<r:require modules="codeMirror, fancyBox, imageUpload, wikiEditor" />



<div class="control-group">
    <label class="control-label">Submitter</label>

    <div class="controls">
        <label class="checkbox" style="padding-left: 0px;">
            <g:link controller="user" action="show" id="${testimonialInstance?.submittedBy?.id}">
                <avatar:gravatar email="${testimonialInstance?.submittedBy?.email}"
                                 size="16"/> ${testimonialInstance?.submittedBy?.email}
            </g:link>
        </label>
    </div>
</div>

<div class="control-group ${hasErrors(bean: testimonialInstance, field: 'title', 'error')}">
    <label class="control-label" for="title">Title</label>

    <div class="controls">
        <g:textField name="title" value="${testimonialInstance?.title}" class="input-xxlarge"/>
    </div>
</div>


<div class="control-group ${hasErrors(bean: testimonialInstance, field: 'companyName', 'error')}">
    <label class="control-label" for="title">Company Name</label>

    <div class="controls">
        <g:textField name="companyName" value="${testimonialInstance?.companyName}" class="input-xxlarge"/>
    </div>
</div>

<div class="control-group ${hasErrors(bean: testimonialInstance, field: 'featured', 'error')}">
    <label class="control-label" for="featured">Is Featured?</label>

    <div class="controls">
        <label class="checkbox" for="featured">
            <g:checkBox name="featured" value="${testimonialInstance?.featured}"/>
            Check this box if the testimonial is featured on the <a href="/community/testimonial"
                                                                target="_blank">/community/testimonial</a> page.
        </label>
    </div>
</div>

<p><g:message code="testimonial.body.description"/></p>

<wiki:uploadImages prefix="testimonial${Testimonial.count() + 1}" />

<g:textArea name="body" class="wiki" rows="40" cols="130" value="${testimonialInstance?.body}"/>

</fieldset>

grails-app/views/testimonialAdmin/create.gsp
<%@ page import="org.grails.community.Testimonial" %>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="layout" content="admin"/>
    <g:set var="entityName" value="${message(code: 'testimonial.label', default: 'Testimonial')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>

<h1 class="page-header">
    <g:message code="default.create.label" args="[entityName]"/>
    <span class="pull-right">
        <g:link class="btn" action="list"><g:message code="default.list.label" args="[entityName]"/></g:link>
    </span>
</h1>

<g:if test="${flash.message}">
    <div class="alert alert-info">${flash.message}</div>
</g:if>

<g:hasErrors bean="${testimonialInstance}">
    <div class="alert alert-error">
        <g:renderErrors bean="${testimonialInstance}" as="list"/>
    </div>
</g:hasErrors>

<g:form action="save" class="form-horizontal" >
<fieldset>

    <g:render template="form" model="model" />


    <div class="form-actions">
        <g:submitButton name="create" class="btn btn-primary"
                        value="${message(code: 'default.button.create.label', default: 'Create')}"/>
        <g:link class="btn" action="list">Cancel</g:link>
    </div>
</fieldset>
</g:form>

</body>
</html>

grails-app/views/testimonialAdmin/edit.gsp
<%@ page import="org.grails.community.Testimonial" %>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="layout" content="admin"/>
    <g:set var="entityName" value="${message(code: 'testimonial.label', default: 'Testimonial')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>

<h1 class="page-header">
    <g:message code="default.edit.label" args="[entityName]"/>
    <span class="pull-right">
        <g:link class="btn" action="list"><g:message code="default.list.label" args="[entityName]"/></g:link>
        <g:link class="btn" action="create"><g:message code="default.create.label" args="[entityName]"/></g:link>
    </span>
</h1>

<g:if test="${flash.message}">
    <div class="alert alert-info">${flash.message}</div>
</g:if>

<g:hasErrors bean="${testimonialInstance}">
    <div class="alert alert-error">
        <g:renderErrors bean="${testimonialInstance}" as="list"/>
    </div>
</g:hasErrors>

<g:form method="post" class="form-horizontal" >

<g:hiddenField name="id" value="${testimonialInstance?.id}"/>
<g:hiddenField name="version" value="${testimonialInstance?.version}"/>



    <g:render template="form" model="model" />



    <div class="form-actions">
    <g:actionSubmit action="update" class="btn btn-primary"
                    value="${message(code: 'default.button.update.label', default: 'Update')}"/>
    <g:actionSubmit class="btn btn-danger" action="delete"
                    value="${message(code: 'default.button.delete.label', default: 'Delete')}"
                    onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
    <g:link class="btn" action="list">Cancel</g:link>
</div>

</g:form>

</body>
</html>

grails-app/views/testimonialAdmin/list.gsp
<%@ page import="org.grails.community.Testimonial" %>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="layout" content="admin"/>
    <g:set var="entityName" value="${message(code: 'testimonial.label', default: 'Testimonial')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>

<h1 class="page-header">
    <g:message code="default.list.label" args="[entityName]"/>
    <span class="pull-right">
        <g:link class="btn btn-primary" action="create">
            <g:message code="default.new.label" args="[entityName]"/>
        </g:link>
    </span>
</h1>

<g:if test="${flash.message}">
    <div class="alert alert-info">
        ${flash.message}
    </div>
</g:if>

<table class="table table-bordered table-striped">
    <thead>
    <tr>
        
        <g:sortableColumn property="id"
                          title="${message(code: 'testimonial.id.label', default: 'Id')}"/>

        <th><g:message code="testimonial.submittedBy.label" default="Submitted By"/></th>


        <g:sortableColumn property="title"
                          title="${message(code: 'testimonial.title.label', default: 'Title')}"/>
        

        <g:sortableColumn property="companyName"
                          title="${message(code: 'testimonial.companyName.label', default: 'Company Name')}"/>


        <g:sortableColumn property="featured" title="Is Featured?"/>


        <g:sortableColumn property="status"
                          title="${message(code: 'testimonial.status.label', default: 'Status')}"/>



    </tr>
    </thead>
    <tbody>
    <g:each in="${testimonialInstanceList}" status="i" var="testimonialInstance">
        <tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
            
            <td><g:link action="show"
                        id="${testimonialInstance.id}">${fieldValue(bean: testimonialInstance, field: "id")}</g:link></td>
            
            <td><g:link controller="user" action="show" id="${testimonialInstance?.submittedBy?.id}">
                <avatar:gravatar email="${testimonialInstance?.submittedBy?.email}"
                                 size="16"/> ${testimonialInstance?.submittedBy?.email}
            </g:link></td>

            <td>${fieldValue(bean: testimonialInstance, field: "title")}</td>

            <td>${fieldValue(bean: testimonialInstance, field: "companyName")}</td>

            <td><g:formatBoolean boolean="${testimonialInstance.featured}"/></td>

            <td><common:approvalStatus status="${testimonialInstance.status}" type="badge" /></td>


        </tr>
    </g:each>
    </tbody>
</table>

<div class="pagination">
    <g:paginate total="${testimonialInstanceTotal}"/>
</div>

</body>
</html>

grails-app/views/testimonialAdmin/show.gsp
<%@ page import="org.grails.community.Testimonial" %>
<%@ page import="org.grails.common.ApprovalStatus"  %>


<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="layout" content="admin"/>
    <g:set var="entityName" value="${message(code: 'testimonial.label', default: 'Testimonial')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
    <r:require modules="fancyBox"/>

</head>

<body>

<h1 class="page-header">
    <g:message code="default.show.label" args="[entityName]"/>
    <span class="pull-right">
        <g:form controller="testimonialAdmin">
            <g:hiddenField name="id" value="${testimonialInstance?.id}"/>
            <g:link class="btn" action="list">
                <g:message code="default.list.label" args="[entityName]"/>
            </g:link>
            <g:actionSubmit class="btn btn-info" action="edit"
                            value="${message(code: 'default.button.edit.label', default: 'Edit')}"/>
            <g:actionSubmit class="btn btn-danger" action="delete"
                            value="${message(code: 'default.button.delete.label', default: 'Delete')}"
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
        </g:form>
    </span>
</h1>

<g:if test="${flash.message}">
    <div class="alert alert-info">
        ${flash.message}
    </div>
</g:if>

<table class="table table-bordered table-striped">
    <tbody>
    
    <tr>
        <td class="show-label">
            <g:message code="testimonial.id.label" default="Id"/>
        </td>

        
        <td class="show-value">${fieldValue(bean: testimonialInstance, field: "id")}</td>
        
    </tr>
    
    <tr>
        <td class="show-label">
            <g:message code="testimonial.title.label" default="Title"/>
        </td>

        
        <td class="show-value">${fieldValue(bean: testimonialInstance, field: "title")}</td>
        
    </tr>
    
    <tr>
        <td class="show-label">
            <g:message code="testimonial.status.label" default="Status"/>
        </td>

        
            <td class="show-value"><common:approvalStatus status="${testimonialInstance.status}" type="badge" /></td>
        
    </tr>
    
    <tr>
        <td class="show-label">
            <g:message code="testimonial.submittedBy.label" default="Submitted By"/>
        </td>

        
        <td class="show-value">
            <g:link controller="user" action="show" id="${testimonialInstance?.submittedBy?.id}">
                <avatar:gravatar email="${testimonialInstance?.submittedBy?.email}"
                                 size="16"/> ${testimonialInstance?.submittedBy?.email}
            </g:link>
            </td>
        
    </tr>

    <tr>
        <td class="show-label">
            <g:message code="testimonial.companyName.label" default="Company Name"/>
        </td>

        
        <td class="show-value">${fieldValue(bean: testimonialInstance, field: "companyName")}</td>
        
    </tr>

    
    <tr>
        <td class="show-label">
            <g:message code="testimonial.featured.label" default="Featured"/>
        </td>

        
            <td class="show-value">${testimonialInstance?.featured ? 'Yes' : 'No'}</td>
        
    </tr>


    <tr>
        <td class="show-label">Responses</td>
        <td>
            <dl style="margin: 0px;">
                <g:each in="${testimonialInstance.genericApprovalResponses}" var="${resp}">
                    <dt>${resp.moderatedBy?.login} marked submission as <common:approvalStatus status="${resp.status}"/> on ${resp.dateCreated}
                    <dd><blockquote>${resp.responseText}</blockquote></dd>
                    </dt>
                </g:each>
            </dl>
        </td>
    </tr>
    
    </tbody>
</table>


<h2>Content</h2>
<wiki:shorten length="100" wikiText="${testimonialInstance.body}" />

<p><a class="btn preview" data-contents="${testimonialInstance.body?.encodeAsHTML()}">Preview</a></p>

<h2 class="page-header">Respond to Submitter</h2>
<g:form class="form-horizontal" action="disposition">
    <fieldset>
        <g:hiddenField name="id" value="${testimonialInstance.id}"/>

        <div class="control-group">
            <label class="control-label" for="status">Request has been:</label>

            <div class="controls">
                <select name="status" id="status">
                    <option value=""></option>
                    <option value="${ApprovalStatus.APPROVED}">APPROVED</option>
                    <option value="${ApprovalStatus.REJECTED}">REJECTED</option>
                </select>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="responseText">Response (for email):</label>

            <div class="controls">
                <textarea cols="50" rows="10" style="width: 99%;" name="responseText" id="responseText"></textarea>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="featured">Is Featured?</label>

            <div class="controls">
                <label class="checkbox" for="featured">
                    <g:checkBox name="featured" value="${testimonialInstance?.featured}"/>
                    Check this box if the website is featured on the Testimonials page.
                </label>
            </div>
        </div>

        <div class="form-actions">
            <g:submitButton id="submit-btn" name="submit" class="btn btn-primary"
                            value="Send Response to Submitter"
                            onclick="return confirm('Are you sure?');"/>
        </div>
    </fieldset>
</g:form>

<r:script>
    $(function () {
        // Show preview of wiki content
        $('.preview').click(function() {
            var body = $(this).data('contents');
            $.ajax({
                type    : "POST",
                cache   : false,
                url     : "/previewWikiPage",
                data    : { body: body },
                success : function(data) {
                    $.fancybox(data, {
                        maxWidth    : 710,
                        maxHeight   : 600,
                        fitToView   : false,
                        width       : '70%',
                        height      : '70%',
                        autoSize    : false,
                        closeClick  : false,
                        openEffect  : 'fade',
                        closeEffect : 'fade'
                    });
                }
            });
            return false;
        });
    });
</r:script>

</body>
</html>